name: Lighthouse Performance Audit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run weekly performance audits
    - cron: '0 9 * * 1'

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: following-christ-thru-paul-website/package-lock.json
          
      - name: Install dependencies
        working-directory: following-christ-thru-paul-website
        run: npm ci
        
      - name: Build application
        working-directory: following-christ-thru-paul-website
        run: npm run build
        env:
          NEXT_PUBLIC_SANITY_PROJECT_ID: dmowh6jp
          NEXT_PUBLIC_SANITY_DATASET: production
          NEXT_PUBLIC_SANITY_API_VERSION: 2025-07-02
          
      - name: Start application
        working-directory: following-christ-thru-paul-website
        run: npm start &
        env:
          NEXT_PUBLIC_SANITY_PROJECT_ID: dmowh6jp
          NEXT_PUBLIC_SANITY_DATASET: production
          NEXT_PUBLIC_SANITY_API_VERSION: 2025-07-02
          
      - name: Wait for server
        run: npx wait-on http://localhost:3000
        
      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v10
        with:
          configPath: following-christ-thru-paul-website/.lighthouserc.json
          uploadArtifacts: true
          temporaryPublicStorage: true
          
      - name: Comment PR with Lighthouse results
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            
            // Read Lighthouse results
            const resultsPath = path.join(process.cwd(), '.lighthouseci');
            if (fs.existsSync(resultsPath)) {
              const comment = `
              ## 🚨 Lighthouse Performance Audit Results
              
              Performance audit completed! Check the detailed results in the action logs.
              
              **Key Metrics Checked:**
              - ✅ Performance: ≥75%
              - ✅ Accessibility: ≥95%
              - ✅ Best Practices: ≥90%
              - ✅ SEO: ≥95%
              
              View full report in the [Lighthouse CI action](${context.payload.pull_request.html_url}/checks).
              `;
              
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: comment
              });
            }